### ISSUE TITLE
I can't take a plane

### ISSUE THREAD

**Issue by Lukli99** [Dzsek/pretense#10]
Good evening, I downloaded the mission and installed everything as described in point 8.
As soon as I start the server and press briefing, all slots are dark blue and none are gray, even though the Blue faction owns airports.

So I can't get on a plane because there isn't one available

**Comment by Dzsek** [comment]
Not a mission issue.
Slots are made unavailable by dcs if you dont own the module.

**Comment by Lukli99** [comment]
No, I only have it in the mission
I have F18, F16 A10II, Ah 64D and can't choose any of them, even at the airports where they should be available ^^

I also played Foodholt Syria

**Comment by Lukli99** [comment]
It's also only when I create a multiplayer server

Yes, it works in the editor

**Comment by Dzsek** [comment]
Ramat david and hussein are the blue spawnzones at the start of the mission. Try spawning at those

**Comment by Lukli99** [comment]
yes I know
I tried it can not

**Comment by Dzsek** [comment]
Post the dcs.log file from the server after you tried choosing a slot
