### ISSUE TITLE
Mission Script Error on Dedicated Server

### ISSUE THREAD

**Issue by albrechtw** [Dzsek/pretense#14]
Hi, When launching Pretense Syria/Modern Syria on DCS dedicated Server 2.8.7.42718 with persistance enabled and slotblock configured I get the following Mission Script Error when starting the miz file on the server:
![image](https://github.com/Dzsek/pretense/assets/38526948/aacbc3c3-87d1-43c4-9a22-e7ce896f4abd)
![image](https://github.com/Dzsek/pretense/assets/38526948/e2fc5922-8a72-4c5c-96ab-42e03307a6dc)

Any help is highly appreciated - Thanks in advance

**Comment by Dzsek** [comment]
Please use dcs open beta.
Pretense makes use of some new scripting api features that did not make it over to the stable branch yet.
