### ISSUE TITLE
Ships draw in suddenly

### ISSUE THREAD

**Issue by freeflow66** [Dzsek/pretense#16]
When flying over the ocean, Cargo Vessels draw into the game very quickly. So instead of seeing them from 10 miles away, they pop up in front of you from only a mile or so, and if you are conducting a low-level attack, it means that often you don't see them until it's too late. I have died several times this way.

Other people are having the same issue:

At first, I thought it was DCS however it does not happen in other missions or in fact in single player. ED have viewed the file and say that the ship model in the track is not one of theirs. So it seems to be a Pretense issue.  Did you change something in the mission to make these static ships draw in faster at a closer range? If not, I'm stumped. If you did, then how can I change it back as when doing low-level attacks >200ft, I quite often hit ships that draw in too fast for me to avoid them.

You can view the track file here: https://1drv.ms/u/s!Ao0tl45yKneTgnrxt6EAwIBzqmNj?e=ppBKpV
[Reply](javascript:void(0))  [Link](https://www.digitalcombatsimulator.com/en/files/3332520/#79330)

**Comment by Dzsek** [comment]
I have no control over that from the mission editor

**Comment by freeflow66** [comment]
I asked DCS, and they say that the ships that appear and disappear are not their standard models and, therefore, they can do nothing about it. If you used non-standard models, maybe they could be deleted from the mission.

**Comment by Dzsek** [comment]
I have not added any ship units or statics to any of my ptetense missions and i can not change map objects.
