### ISSUE TITLE
An error occurred while running on the server

### ISSUE THREAD

**Issue by RottenHB** [Dzsek/pretense#17]
An error occurred when running on the server. How can I solve it?
![微信图片_20231205162429](https://github.com/Dzsek/pretense/assets/58563288/f24870d6-baef-46fc-b076-1cc29370c742)

**Comment by Dzsek** [comment]
Make sure you've edited missionscripting.lua on the server according to instructions in the manual and check that dcs has write access to savegames/dcs/missions/saves folder.

**Comment by RottenHB** [comment]
> 确保您已根据手册中的说明在服务器上编辑了missionscripting.lua，并检查dcs是否具有对savegames/dcs/missions/saves文件夹的写入权限。

Thank you for your help. I am sure that I have modified everything as required and half of the positions have been occupied. I have been playing with my friends for about a week and there has been no problem. It is only now that this error message appears after half of the positions have been occupied.

**Comment by RottenHB** [comment]
> Make sure you've edited missionscripting.lua on the server according to instructions in the manual and check that dcs has write access to savegames/dcs/missions/saves folder.

Thank you for your help. I am sure that I have modified everything as required and half of the positions have been occupied. I have been playing with my friends for about a week and there has been no problem. It is only now that this error message appears after half of the positions have been occupied.

**Comment by Dzsek** [comment]
Check if the save file is at the right location and that it contains valid json text.

**Comment by RottenHB** [comment]
> Check if the save file is at the right location and that it contains valid json text.

Checked, everything is there
![1701783092448](https://github.com/Dzsek/pretense/assets/58563288/abee4dcb-05f3-4cdc-9cd1-35025adb2fcd)

**Comment by Dzsek** [comment]
I have no idea what could be wrong then, you can try moving those files out and see if you can fix it that way by resetting your save. If it does then the save was corrupted
