### ISSUE TITLE
Question about DataLink on Mission Files

### ISSUE THREAD

**Issue by pedrohugorm** [Dzsek/pretense#23]
Hello, I'm relatively new to DCS and I downloaded and ran The Caucasus (both hot and cold versions) and Syria Pretense (Not the Cold War one) missions.

I noticed that the datalink doesn't work.
I first assumed my INS alignment on the F-16 was the issue so I did:

* Aligned the F-16 down to /10 using Stored Aligned and Using the Norm alignment
  * DL was ON
  * GPS was ON
  * All the switches around MMC -> MAP are ON
  * MDS LYT  = ON
  * INS = NAV

* I also tried running the hot mission, since the aircraft would be already pre-setup to fly.
  * Same result.
  * Alignment on hot aircraft is at the /6
 
* I spawned an AWACS as well and tuned in to the AM Freq of 124 on the F-16

* A friend with more experience than I also tried on the F/A 18 to compare and the same was observed.

* I also tried an empty mission file and the datalink works

* I'm wondering if the mission is setup on purpose to not have it working or if there's something else I might be missing on the aircraft.

I'm asking here now to see if there are any settings I should be tweaking on the mission files to get it to work.

I'm using the latest version 1.5 as of this date of the mission files.

Any help appreciated.

Test done on an new map (not a pretense map):
Yields correct results
![image](https://github.com/Dzsek/pretense/assets/847076/18ff63a6-c53f-435f-a79d-911595ee5491)

And I didn't have any donors setup on the 16. It just works.
![image](https://github.com/Dzsek/pretense/assets/847076/573f19ad-2b29-4924-a557-ee33930f2db4)

That just makes me think there's some config on the mission.

**Comment by Dzsek** [comment]
Datalink on the F-16 is currently bugged in the latest open beta version.
To get it to work you need to toggle GPS time OFF and ON again in the LIST->DLNK page.
![image](https://github.com/Dzsek/pretense/assets/19503259/50c478fb-029a-4ff9-88d1-97948fa83e5b)
