### ISSUE TITLE
Survival multiplier never [SECURED] && ATC does not respond

### ISSUE THREAD

**Issue by ButterMeWaffle** [Dzsek/pretense#26]
#1 Survival multiplier never [SECURED]
I have been running a private Pretense Caucasus region server for a friend and myself for the past few weeks. First off its great fun, thanks for making and sharing this! However I have been running into an issue with securing the survival multiplier. Per the readme "You can secure your multiplier by landing at a friendly zone and shutting down your engines.". This feature seems to have some issues no matter what type of aircraft we try it on. I wasnt able to find anything about a setup process to make this work so I assume it works "out of the box" so to speak. This leads me to believe there is some kind of bug in the code for this particular feature.

Does anyone have a similar experience or know a possible fix? We really enjoy completing a mission in a specific aircraft then swapping to fly a different type of mission but we are missing out on our sweet sweet survival multiplier! Any help would be greatly appreciated.

#2 ATC does not respond
Another, to me, less important issue im seeing is that ATC almost never responds when asking for landing. I have had it work maybe 1% of the time and im not sure what was done differently to make it work that time. Normally it isnt a big deal but when the server turns to night it can make landing nearly impossible as I cant get ATC to turn the lights on or give me a heading of any kind. Atm we reset the server (with persistence) to change back to daytime but I would love to be able to fly at night again!

Currently my server is also running the slmod, however the issue was present before I added slmod and it is the only mod on my server. Otherwise it is bare bones open-beta running the newest release.

**Comment by Dzsek** [comment]
1. Make sure you have the latest version, that was only implemented recently.

2. Easy comms is off by default in this mission. You need to tune the correct frequency for the airfield and use the correct radio.

**Comment by ButterMeWaffle** [comment]
@Dzsek Thanks for the incredibly quick response

1. would here on github be the best spot to get the latest then? I believe I got my file from the WCS community files page. And if I were to use a newer version, would I lose the persistence of my current save?

2. Okay now I feel dumb, that makes a lot of sense and I should have thought about that. Thank you!

**Comment by Dzsek** [comment]
Dcs userfiles always has the newest one.

You can find what the latest version number is at the end of the manual in the changelog.

**Comment by ButterMeWaffle** [comment]
wow you made a lot of changes since I downloaded it in December. I didnt expect that, thanks for the help and all the time you've put into this!

Final question about the persistence. Will I be safe to upgrade without restarting the missing from "day 1"?

**Comment by Dzsek** [comment]
Regarding your save, check the changelog, it will be noted there if a particular version reset the progress.

In this case 1.6 did, so upgrading from before that will reset it.

**Comment by ButterMeWaffle** [comment]
gotcha, ill keep a better eye on the project and change logs in the future. Thanks again, I will close this issue out

**Comment by ButterMeWaffle** [comment]
@Dzsek sorry I know i said that was my last but I cant seem to find v1.5.2 anywhere, do you have a repo with the previous versions?

**Comment by Dzsek** [comment]
[Pretense_1.5.2.zip](https://github.com/Dzsek/pretense/files/14152086/Pretense_1.5.2.zip)
I dont keep a public archive but I do have past builds. Here.
