### ISSUE TITLE
Tents and fuel tanks can't be destroyed by guns rockets or missiles.

### ISSUE THREAD

**Issue by DragonDal** [Dzsek/pretense#31]
Hi there ,

Some objectives Tents and fuel tanks can't be destroyed by guns ,missiles or rockets. But is erratic. Players can have issues . Then leave the server , come back another time and they get destroyed normally. Happens on different objectives . Not always the same objectives . Is this a bug in DCS ???

**Comment by Dzsek** [comment]
Dcs issue

**Comment by DragonDal** [comment]
Ok thank you for the update. Just was curious. I appreciated
