### ISSUE TITLE
Script error - attempt index a nil value

### ISSUE THREAD

**Issue by sancron** [Dzsek/pretense#32]
2024-03-10 23:35:52.154 INFO    SCRIPTING (Main): GroupMonitor: processAir [sukhumi-cas-red] despawned after landing
2024-03-10 23:35:52.156 ERROR   SCRIPTING (Main): Mission script error: [string "C:\Users\Administrator\Saved Games\DCS.ironeagles_server2\/MissionScripts/Pretense/Caucasus/pretense_compiled.lua"]:2485: attempt to index a nil value
stack traceback:
	[C]: ?
	[string "C:\Users\Administrator\Saved Games\DCS.ironeagles_server2\/MissionScripts/Pretense/Caucasus/pretense_compiled.lua"]:2485: in function 'processAir'
	[string "C:\Users\Administrator\Saved Games\DCS.ironeagles_server2\/MissionScripts/Pretense/Caucasus/pretense_compiled.lua"]:2103: in function <[string "C:\Users\Administrator\Saved Games\DCS.ironeagles_server2\/MissionScripts/Pretense/Caucasus/pretense_compiled.lua"]:2092>

**Comment by AlexZanderD** [comment]
Find the line in **pretense_compiled.lua**
`if gr and gr:getSize()>0 and gr:getUnit(1):isExist() then`
and replace it to
`if gr and gr:getSize()>0 and gr:getUnit(1).isExist and gr:getUnit(1):isExist() then`

**Comment by AlexZanderD** [comment]
> Should i replace both lines since i find two
> 
> 2485 (Pretense 1.7.2 file) ` if group.state =='takeoff' then if timer.getAbsTime() - group.lastStateTime > GroupMonitor.blockedDespawnTime then if gr and gr:getSize()>0 and gr:getUnit(1):isExist() then`
> 
> Also line 10134 ` if group.state == CarrierCommand.supportStates.none then setState(group, CarrierCommand.supportStates.takeoff) env.info('CarrierCommand: processAir ['..group.name..'] started existing state=takeoff') elseif group.state == CarrierCommand.supportStates.takeoff then if timer.getAbsTime() - group.lastStateTime > CarrierCommand.blockedDespawnTime then if gr and gr:getSize()>0 and gr:getUnit(1):isExist() then`

Yes.

**Comment by dapayne12** [comment]
This fix didn't work for me. I encountered the error again a few days later. I'm now using this line in both locations:

```
if gr and gr:getSize()>0 and gr:getUnit(1) != nil and gr:getUnit(1):isExist() then
```

So far so good.

@sancron, I would suggest keeping the issue open until the issue is fixed in a release from Dzsek.
