### ISSUE TITLE
Reducing Heli Spawns

### ISSUE THREAD

**Issue by chiponn** [Dzsek/pretense#7]
Hi, 

In a smaller playing server, I find it incredibly hard to capture zones due to the rate of MI-8 spawns. 
Is there a way to reduce the rate of heli spawns? If not, I would be happy to see this implemented. 

If there is a way, I'll be happy if you can share the solution. 

Thank you.

**Comment by Dzsek** [comment]
Spawn rates are controlled by build times and available resources. Check the manual section 6 for how to adjust build speeds.
You can adjust build speed for supply missions, which include convoys as well as helicopters.

There is no setting specifically for helicopters, and settings will always affect both coalitions, as the mission is designed for both of them to play by the same rules.
