### ISSUE TITLE
Multicrew Bug in Mission

### ISSUE THREAD

**Issue by fingerratte** [Dzsek/pretense#8]
Me and friends tested your mission in multiplayer (pretense Caucasus) and found out that the ability for users to deny joining an aircraft in multicrew doesn't work here. Unfortunately, this becomes a tragedy for trolls who simply get in on your aircraft and mess up. And there's nothing you can do about it - it seems that the function to accept or block a player is completly bypassed. 

I suspect this function here, is causing this bypass. I don't know if you use it... Please Help, we like your mission - but this make it unplayable on Public Servers for us. 

May take a look please: 
https://wiki.hoggitworld.com/view/DCS_hook_onPlayerTryChangeSlot

 "DCS itself uses this callback as part of the multicrew slot interface".

**Comment by GoldJohnKing** [comment]
No, it is not this function.

**Comment by Dzsek** [comment]
The slotblock script from Pretense only denies the slot if the slot is not in a friendly zone.
It does not specifically allow anyone into a slot. For a script like this to bypass the normal UI it has to explicitly return True somewhere.

Please check if you have any other scripts using the onPlayerTryChangeSlot hook, Pretense should not be causing this.
