### ISSUE TITLE
Feature Request - add bool to allow missions to be accepted/joined while in air.

### ISSUE THREAD

**Issue by Drofseh** [Dzsek/pretense#9]
I'd love it if a config option could be added to allow players to accept or join missions after a player has taken off.

`Config.allowMissionAcceptanceWhileFlying = True` or something like that.

This would allow a player who had a technical issue to reslot and still join the mission.

**Comment by GoldJohnKing** [comment]
As a workaround, you may modify `function MissionTracker:joinMission` in `pretense_compiled.lua` (line 12498) yourself.

Comment out (line 12523):
```
        if mis.state ~= Mission.states.preping then
            trigger.action.outTextForUnit(unit:getID(), 'Mission can only be joined if its members have not taken off yet.', 5)
            return false 
        end
```

Not sure if there's any side effect, you may try it out yourself.

**Comment by Drofseh** [comment]
Yeah I'm going to give that a try, as well as commenting this out a few lines above
```
if not unit or not unit:isExist() or not Utils.isLanded(unit, true) then 
    if unit and unit:isExist() then trigger.action.outTextForUnit(unit:getID(), 'Can only join mission while landed', 5) end
    return false
end
```

**Comment by AlexZanderD** [comment]
Or even better: you can accept mission only while you're on the ground but when mission completed then you can accept another one and get reward for both after landing.

**Comment by Dzsek** [comment]
will be in next patch
